### 현재 로그인 사용자 조회

GET http://localhost:8080/me
Authorization: Basic YWRtaW46YWRtaW4xMjM0

### 권한 테스트

GET http://localhost:8080/permission/check?departmentId=IT&securityLevel=3
Authorization: Basic YWRtaW46YWRtaW4xMjM0


### 대화 저장

POST http://localhost:8080/conversations
Authorization: Basic YWRtaW46YWRtaW4xMjM0
Content-Type: application/json

{
  "question": "Spring AI란 무엇인가요?",
  "answer": "Spring 기반 AI 개발 프레임워크입니다."
}

### 대화 목록 조회

GET http://localhost:8080/conversations
Authorization: Basic YWRtaW46YWRtaW4xMjM0


### AI 호출
POST http://localhost:8080/conversations
Authorization: Basic YWRtaW46YWRtaW4xMjM0
Content-Type: application/json

{
  "question": "Spring AI가 무엇인가요?"
}


### Step7 - 문서 업로드
POST http://localhost:8080/documents/extract
Authorization: Basic YWRtaW46YWRtaW4xMjM0
Content-Type: multipart/form-data; boundary=DocumentBoundary

--DocumentBoundary
Content-Disposition: form-data; name="file"; filename="sample.pdf"
Content-Type: application/pdf

< ./sample.pdf
--DocumentBoundary--



### Step 8-1 - Embedding 생성 테스트
GET http://localhost:8080/embeddings?text=퇴직금은%20어떻게%20계산하나요
Authorization: Basic YWRtaW46YWRtaW4xMjM0