spring.application.name=springAI

# ===============================
# H2 Database
# ===============================
#spring.datasource.url=jdbc:h2:mem:springai;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.url=jdbc:h2:file:./data/springai;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# JPA
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===============================
# H2 Console
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===============================
# Spring AI Chat
# ===============================
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.chat.model=gemini-2.5-flash
spring.ai.google.genai.chat.temperature=0.3
spring.ai.google.genai.chat.max-output-tokens=1000
# spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
# spring.ai.google.genai.embedding.text.model=text-embedding-004

# ===============================
# Spring AI Embedding
# ===============================
spring.ai.model.embedding.text=none